# Form implementation generated from reading ui file 'BinaryDecimalCalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# This was made using PyQt5 Designer and translated from .ui to .py file with the pyuic5 cmd command

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt


# The Design
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Binary to Decimal")
        MainWindow.resize(423, 139)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 20, 361, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 50, 108, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 50, 111, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 423, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
# When the buttons are clicked the functions are called
        self.pushButton.clicked.connect(self.encrypt)
        self.pushButton_2.clicked.connect(self.decrypt)


# Setting the text to the buttons and the title of the window
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Binary to Decimal", "Binary to Decimal"))
        self.pushButton.setText(_translate("Binary to Decimal", "Decimal to Binary"))
        self.pushButton_2.setText(_translate("Binary to Decimal", "Binary to Decimal"))

# Decimal to binary function
    def encrypt(self):
        text = self.lineEdit.text()
        end = ""
        text_splited = text.split(".")
        if text:
            for item in text_splited:
                a = int(item)
                if a <= 128 or a >= 128:
                    if a >= 128:
                        end += "1"
                        a = a - 128
                    elif a <= 128:
                        end += "0"

                if a <= 64 or a >= 64:
                    if a >= 64:
                        end += "1"
                        a = a - 64
                    elif a <= 64:
                        end += "0"

                if a <= 32 or a >= 32:
                    if a >= 32:
                        end += "1"
                        a = a - 32
                    elif a <= 32:
                        end += "0"

                if a <= 16 or a >= 16:
                    if a >= 16:
                        end += "1"
                        a = a - 16
                    elif a <= 16:
                        end += "0"

                if a <= 8 or a >= 8:
                    if a >= 8:
                        end += "1"
                        a = a - 8
                    elif a <= 8:
                        end += "0"
                if a <= 4 or a >= 4:
                    if a >= 4:
                        end += "1"
                        a = a - 4
                    elif a <= 4:
                        end += "0"

                if a <= 2 or a >= 2:
                    if a >= 2:
                        end += "1"
                        a = a - 2
                    elif a <= 2:
                        end += "0"

                if a <= 1 or a >= 1:
                    if a >= 1:
                        end += "1"
                        a = a - 1
                    elif a <= 1:
                        end += "0"
                end += "."
        new_string = end[:-1]
        msg_box = QtWidgets.QMessageBox()
        msg_box.setWindowTitle("Result")
        msg_box.setText(new_string)
        msg_box.setTextInteractionFlags(Qt.TextSelectableByMouse)
        msg_box.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msg_box.exec_()
# Binary to decimal function
    def decrypt(self):
        text = self.lineEdit.text()
        binary_splited = text.split(".")
        end = ""
        for binary in binary_splited:
            decimal = 0
            power = len(str(binary)) - 1
            for digit in str(binary):
                decimal += int(digit) * 2 ** power
                power -= 1
            end += str(decimal)
            end += "."
        new_end = end[:-1]

        msg_box = QtWidgets.QMessageBox()
        msg_box.setWindowTitle("Result")
        msg_box.setText(new_end)
        msg_box.setTextInteractionFlags(Qt.TextSelectableByMouse)
        msg_box.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msg_box.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
